// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SophonPatchProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Hi3Helper.Sophon.Protos {

  /// <summary>Holder for reflection information generated from SophonPatchProto.proto</summary>
  public static partial class SophonPatchProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for SophonPatchProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SophonPatchProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZTb3Bob25QYXRjaFByb3RvLnByb3RvEhdIaTNIZWxwZXIuU29waG9uLlBy",
            "b3RvcyKkAQoQU29waG9uUGF0Y2hQcm90bxJGCgtQYXRjaEFzc2V0cxgBIAMo",
            "CzIxLkhpM0hlbHBlci5Tb3Bob24uUHJvdG9zLlNvcGhvblBhdGNoQXNzZXRQ",
            "cm9wZXJ0eRJICgxVbnVzZWRBc3NldHMYAiADKAsyMi5IaTNIZWxwZXIuU29w",
            "aG9uLlByb3Rvcy5Tb3Bob25VbnVzZWRBc3NldFByb3BlcnR5IpkBChhTb3Bo",
            "b25QYXRjaEFzc2V0UHJvcGVydHkSEQoJQXNzZXROYW1lGAEgASgJEhEKCUFz",
            "c2V0U2l6ZRgCIAEoAxIUCgxBc3NldEhhc2hNZDUYAyABKAkSQQoKQXNzZXRJ",
            "bmZvcxgEIAMoCzItLkhpM0hlbHBlci5Tb3Bob24uUHJvdG9zLlNvcGhvblBh",
            "dGNoQXNzZXRJbmZvImkKFFNvcGhvblBhdGNoQXNzZXRJbmZvEhIKClZlcnNp",
            "b25UYWcYASABKAkSPQoFQ2h1bmsYAiABKAsyLi5IaTNIZWxwZXIuU29waG9u",
            "LlByb3Rvcy5Tb3Bob25QYXRjaEFzc2V0Q2h1bmsi7QEKFVNvcGhvblBhdGNo",
            "QXNzZXRDaHVuaxIRCglQYXRjaE5hbWUYASABKAkSEgoKVmVyc2lvblRhZxgC",
            "IAEoCRIPCgdCdWlsZElkGAMgASgJEhEKCVBhdGNoU2l6ZRgEIAEoAxIQCghQ",
            "YXRjaE1kNRgFIAEoCRITCgtQYXRjaE9mZnNldBgGIAEoAxITCgtQYXRjaExl",
            "bmd0aBgHIAEoAxIYChBPcmlnaW5hbEZpbGVOYW1lGAggASgJEhoKEk9yaWdp",
            "bmFsRmlsZUxlbmd0aBgJIAEoAxIXCg9PcmlnaW5hbEZpbGVNZDUYCiABKAki",
            "cwoZU29waG9uVW51c2VkQXNzZXRQcm9wZXJ0eRISCgpWZXJzaW9uVGFnGAEg",
            "ASgJEkIKCkFzc2V0SW5mb3MYAiADKAsyLi5IaTNIZWxwZXIuU29waG9uLlBy",
            "b3Rvcy5Tb3Bob25VbnVzZWRBc3NldEluZm8iVwoVU29waG9uVW51c2VkQXNz",
            "ZXRJbmZvEj4KBkFzc2V0cxgBIAMoCzIuLkhpM0hlbHBlci5Tb3Bob24uUHJv",
            "dG9zLlNvcGhvblVudXNlZEFzc2V0RmlsZSJMChVTb3Bob25VbnVzZWRBc3Nl",
            "dEZpbGUSEAoIRmlsZU5hbWUYASABKAkSEAoIRmlsZVNpemUYAiABKAMSDwoH",
            "RmlsZU1kNRgDIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.Sophon.Protos.SophonPatchProto), global::Hi3Helper.Sophon.Protos.SophonPatchProto.Parser, new[]{ "PatchAssets", "UnusedAssets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.Sophon.Protos.SophonPatchAssetProperty), global::Hi3Helper.Sophon.Protos.SophonPatchAssetProperty.Parser, new[]{ "AssetName", "AssetSize", "AssetHashMd5", "AssetInfos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.Sophon.Protos.SophonPatchAssetInfo), global::Hi3Helper.Sophon.Protos.SophonPatchAssetInfo.Parser, new[]{ "VersionTag", "Chunk" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.Sophon.Protos.SophonPatchAssetChunk), global::Hi3Helper.Sophon.Protos.SophonPatchAssetChunk.Parser, new[]{ "PatchName", "VersionTag", "BuildId", "PatchSize", "PatchMd5", "PatchOffset", "PatchLength", "OriginalFileName", "OriginalFileLength", "OriginalFileMd5" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty), global::Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty.Parser, new[]{ "VersionTag", "AssetInfos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo), global::Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo.Parser, new[]{ "Assets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Hi3Helper.Sophon.Protos.SophonUnusedAssetFile), global::Hi3Helper.Sophon.Protos.SophonUnusedAssetFile.Parser, new[]{ "FileName", "FileSize", "FileMd5" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SophonPatchProto : pb::IMessage<SophonPatchProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SophonPatchProto> _parser = new pb::MessageParser<SophonPatchProto>(() => new SophonPatchProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SophonPatchProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.Sophon.Protos.SophonPatchProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchProto(SophonPatchProto other) : this() {
      patchAssets_ = other.patchAssets_.Clone();
      unusedAssets_ = other.unusedAssets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchProto Clone() {
      return new SophonPatchProto(this);
    }

    /// <summary>Field number for the "PatchAssets" field.</summary>
    public const int PatchAssetsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Hi3Helper.Sophon.Protos.SophonPatchAssetProperty> _repeated_patchAssets_codec
        = pb::FieldCodec.ForMessage(10, global::Hi3Helper.Sophon.Protos.SophonPatchAssetProperty.Parser);
    private readonly pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonPatchAssetProperty> patchAssets_ = new pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonPatchAssetProperty>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonPatchAssetProperty> PatchAssets {
      get { return patchAssets_; }
    }

    /// <summary>Field number for the "UnusedAssets" field.</summary>
    public const int UnusedAssetsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty> _repeated_unusedAssets_codec
        = pb::FieldCodec.ForMessage(18, global::Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty.Parser);
    private readonly pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty> unusedAssets_ = new pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetProperty> UnusedAssets {
      get { return unusedAssets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SophonPatchProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SophonPatchProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!patchAssets_.Equals(other.patchAssets_)) return false;
      if(!unusedAssets_.Equals(other.unusedAssets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= patchAssets_.GetHashCode();
      hash ^= unusedAssets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      patchAssets_.WriteTo(output, _repeated_patchAssets_codec);
      unusedAssets_.WriteTo(output, _repeated_unusedAssets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      patchAssets_.WriteTo(ref output, _repeated_patchAssets_codec);
      unusedAssets_.WriteTo(ref output, _repeated_unusedAssets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += patchAssets_.CalculateSize(_repeated_patchAssets_codec);
      size += unusedAssets_.CalculateSize(_repeated_unusedAssets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SophonPatchProto other) {
      if (other == null) {
        return;
      }
      patchAssets_.Add(other.patchAssets_);
      unusedAssets_.Add(other.unusedAssets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            patchAssets_.AddEntriesFrom(input, _repeated_patchAssets_codec);
            break;
          }
          case 18: {
            unusedAssets_.AddEntriesFrom(input, _repeated_unusedAssets_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            patchAssets_.AddEntriesFrom(ref input, _repeated_patchAssets_codec);
            break;
          }
          case 18: {
            unusedAssets_.AddEntriesFrom(ref input, _repeated_unusedAssets_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SophonPatchAssetProperty : pb::IMessage<SophonPatchAssetProperty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SophonPatchAssetProperty> _parser = new pb::MessageParser<SophonPatchAssetProperty>(() => new SophonPatchAssetProperty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SophonPatchAssetProperty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.Sophon.Protos.SophonPatchProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetProperty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetProperty(SophonPatchAssetProperty other) : this() {
      assetName_ = other.assetName_;
      assetSize_ = other.assetSize_;
      assetHashMd5_ = other.assetHashMd5_;
      assetInfos_ = other.assetInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetProperty Clone() {
      return new SophonPatchAssetProperty(this);
    }

    /// <summary>Field number for the "AssetName" field.</summary>
    public const int AssetNameFieldNumber = 1;
    private string assetName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AssetName {
      get { return assetName_; }
      set {
        assetName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AssetSize" field.</summary>
    public const int AssetSizeFieldNumber = 2;
    private long assetSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AssetSize {
      get { return assetSize_; }
      set {
        assetSize_ = value;
      }
    }

    /// <summary>Field number for the "AssetHashMd5" field.</summary>
    public const int AssetHashMd5FieldNumber = 3;
    private string assetHashMd5_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AssetHashMd5 {
      get { return assetHashMd5_; }
      set {
        assetHashMd5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AssetInfos" field.</summary>
    public const int AssetInfosFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Hi3Helper.Sophon.Protos.SophonPatchAssetInfo> _repeated_assetInfos_codec
        = pb::FieldCodec.ForMessage(34, global::Hi3Helper.Sophon.Protos.SophonPatchAssetInfo.Parser);
    private readonly pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonPatchAssetInfo> assetInfos_ = new pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonPatchAssetInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonPatchAssetInfo> AssetInfos {
      get { return assetInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SophonPatchAssetProperty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SophonPatchAssetProperty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AssetName != other.AssetName) return false;
      if (AssetSize != other.AssetSize) return false;
      if (AssetHashMd5 != other.AssetHashMd5) return false;
      if(!assetInfos_.Equals(other.assetInfos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AssetName.Length != 0) hash ^= AssetName.GetHashCode();
      if (AssetSize != 0L) hash ^= AssetSize.GetHashCode();
      if (AssetHashMd5.Length != 0) hash ^= AssetHashMd5.GetHashCode();
      hash ^= assetInfos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AssetName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AssetName);
      }
      if (AssetSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AssetSize);
      }
      if (AssetHashMd5.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AssetHashMd5);
      }
      assetInfos_.WriteTo(output, _repeated_assetInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AssetName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AssetName);
      }
      if (AssetSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(AssetSize);
      }
      if (AssetHashMd5.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(AssetHashMd5);
      }
      assetInfos_.WriteTo(ref output, _repeated_assetInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AssetName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AssetName);
      }
      if (AssetSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AssetSize);
      }
      if (AssetHashMd5.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AssetHashMd5);
      }
      size += assetInfos_.CalculateSize(_repeated_assetInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SophonPatchAssetProperty other) {
      if (other == null) {
        return;
      }
      if (other.AssetName.Length != 0) {
        AssetName = other.AssetName;
      }
      if (other.AssetSize != 0L) {
        AssetSize = other.AssetSize;
      }
      if (other.AssetHashMd5.Length != 0) {
        AssetHashMd5 = other.AssetHashMd5;
      }
      assetInfos_.Add(other.assetInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AssetName = input.ReadString();
            break;
          }
          case 16: {
            AssetSize = input.ReadInt64();
            break;
          }
          case 26: {
            AssetHashMd5 = input.ReadString();
            break;
          }
          case 34: {
            assetInfos_.AddEntriesFrom(input, _repeated_assetInfos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AssetName = input.ReadString();
            break;
          }
          case 16: {
            AssetSize = input.ReadInt64();
            break;
          }
          case 26: {
            AssetHashMd5 = input.ReadString();
            break;
          }
          case 34: {
            assetInfos_.AddEntriesFrom(ref input, _repeated_assetInfos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SophonPatchAssetInfo : pb::IMessage<SophonPatchAssetInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SophonPatchAssetInfo> _parser = new pb::MessageParser<SophonPatchAssetInfo>(() => new SophonPatchAssetInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SophonPatchAssetInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.Sophon.Protos.SophonPatchProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetInfo(SophonPatchAssetInfo other) : this() {
      versionTag_ = other.versionTag_;
      chunk_ = other.chunk_ != null ? other.chunk_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetInfo Clone() {
      return new SophonPatchAssetInfo(this);
    }

    /// <summary>Field number for the "VersionTag" field.</summary>
    public const int VersionTagFieldNumber = 1;
    private string versionTag_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VersionTag {
      get { return versionTag_; }
      set {
        versionTag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Chunk" field.</summary>
    public const int ChunkFieldNumber = 2;
    private global::Hi3Helper.Sophon.Protos.SophonPatchAssetChunk chunk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Hi3Helper.Sophon.Protos.SophonPatchAssetChunk Chunk {
      get { return chunk_; }
      set {
        chunk_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SophonPatchAssetInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SophonPatchAssetInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VersionTag != other.VersionTag) return false;
      if (!object.Equals(Chunk, other.Chunk)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VersionTag.Length != 0) hash ^= VersionTag.GetHashCode();
      if (chunk_ != null) hash ^= Chunk.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VersionTag.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VersionTag);
      }
      if (chunk_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chunk);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VersionTag.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VersionTag);
      }
      if (chunk_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Chunk);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VersionTag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VersionTag);
      }
      if (chunk_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Chunk);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SophonPatchAssetInfo other) {
      if (other == null) {
        return;
      }
      if (other.VersionTag.Length != 0) {
        VersionTag = other.VersionTag;
      }
      if (other.chunk_ != null) {
        if (chunk_ == null) {
          Chunk = new global::Hi3Helper.Sophon.Protos.SophonPatchAssetChunk();
        }
        Chunk.MergeFrom(other.Chunk);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VersionTag = input.ReadString();
            break;
          }
          case 18: {
            if (chunk_ == null) {
              Chunk = new global::Hi3Helper.Sophon.Protos.SophonPatchAssetChunk();
            }
            input.ReadMessage(Chunk);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VersionTag = input.ReadString();
            break;
          }
          case 18: {
            if (chunk_ == null) {
              Chunk = new global::Hi3Helper.Sophon.Protos.SophonPatchAssetChunk();
            }
            input.ReadMessage(Chunk);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SophonPatchAssetChunk : pb::IMessage<SophonPatchAssetChunk>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SophonPatchAssetChunk> _parser = new pb::MessageParser<SophonPatchAssetChunk>(() => new SophonPatchAssetChunk());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SophonPatchAssetChunk> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.Sophon.Protos.SophonPatchProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetChunk() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetChunk(SophonPatchAssetChunk other) : this() {
      patchName_ = other.patchName_;
      versionTag_ = other.versionTag_;
      buildId_ = other.buildId_;
      patchSize_ = other.patchSize_;
      patchMd5_ = other.patchMd5_;
      patchOffset_ = other.patchOffset_;
      patchLength_ = other.patchLength_;
      originalFileName_ = other.originalFileName_;
      originalFileLength_ = other.originalFileLength_;
      originalFileMd5_ = other.originalFileMd5_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonPatchAssetChunk Clone() {
      return new SophonPatchAssetChunk(this);
    }

    /// <summary>Field number for the "PatchName" field.</summary>
    public const int PatchNameFieldNumber = 1;
    private string patchName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PatchName {
      get { return patchName_; }
      set {
        patchName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "VersionTag" field.</summary>
    public const int VersionTagFieldNumber = 2;
    private string versionTag_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VersionTag {
      get { return versionTag_; }
      set {
        versionTag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "BuildId" field.</summary>
    public const int BuildIdFieldNumber = 3;
    private string buildId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BuildId {
      get { return buildId_; }
      set {
        buildId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PatchSize" field.</summary>
    public const int PatchSizeFieldNumber = 4;
    private long patchSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PatchSize {
      get { return patchSize_; }
      set {
        patchSize_ = value;
      }
    }

    /// <summary>Field number for the "PatchMd5" field.</summary>
    public const int PatchMd5FieldNumber = 5;
    private string patchMd5_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PatchMd5 {
      get { return patchMd5_; }
      set {
        patchMd5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PatchOffset" field.</summary>
    public const int PatchOffsetFieldNumber = 6;
    private long patchOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PatchOffset {
      get { return patchOffset_; }
      set {
        patchOffset_ = value;
      }
    }

    /// <summary>Field number for the "PatchLength" field.</summary>
    public const int PatchLengthFieldNumber = 7;
    private long patchLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PatchLength {
      get { return patchLength_; }
      set {
        patchLength_ = value;
      }
    }

    /// <summary>Field number for the "OriginalFileName" field.</summary>
    public const int OriginalFileNameFieldNumber = 8;
    private string originalFileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OriginalFileName {
      get { return originalFileName_; }
      set {
        originalFileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OriginalFileLength" field.</summary>
    public const int OriginalFileLengthFieldNumber = 9;
    private long originalFileLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OriginalFileLength {
      get { return originalFileLength_; }
      set {
        originalFileLength_ = value;
      }
    }

    /// <summary>Field number for the "OriginalFileMd5" field.</summary>
    public const int OriginalFileMd5FieldNumber = 10;
    private string originalFileMd5_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OriginalFileMd5 {
      get { return originalFileMd5_; }
      set {
        originalFileMd5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SophonPatchAssetChunk);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SophonPatchAssetChunk other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PatchName != other.PatchName) return false;
      if (VersionTag != other.VersionTag) return false;
      if (BuildId != other.BuildId) return false;
      if (PatchSize != other.PatchSize) return false;
      if (PatchMd5 != other.PatchMd5) return false;
      if (PatchOffset != other.PatchOffset) return false;
      if (PatchLength != other.PatchLength) return false;
      if (OriginalFileName != other.OriginalFileName) return false;
      if (OriginalFileLength != other.OriginalFileLength) return false;
      if (OriginalFileMd5 != other.OriginalFileMd5) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PatchName.Length != 0) hash ^= PatchName.GetHashCode();
      if (VersionTag.Length != 0) hash ^= VersionTag.GetHashCode();
      if (BuildId.Length != 0) hash ^= BuildId.GetHashCode();
      if (PatchSize != 0L) hash ^= PatchSize.GetHashCode();
      if (PatchMd5.Length != 0) hash ^= PatchMd5.GetHashCode();
      if (PatchOffset != 0L) hash ^= PatchOffset.GetHashCode();
      if (PatchLength != 0L) hash ^= PatchLength.GetHashCode();
      if (OriginalFileName.Length != 0) hash ^= OriginalFileName.GetHashCode();
      if (OriginalFileLength != 0L) hash ^= OriginalFileLength.GetHashCode();
      if (OriginalFileMd5.Length != 0) hash ^= OriginalFileMd5.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PatchName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PatchName);
      }
      if (VersionTag.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(VersionTag);
      }
      if (BuildId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BuildId);
      }
      if (PatchSize != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(PatchSize);
      }
      if (PatchMd5.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PatchMd5);
      }
      if (PatchOffset != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(PatchOffset);
      }
      if (PatchLength != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(PatchLength);
      }
      if (OriginalFileName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(OriginalFileName);
      }
      if (OriginalFileLength != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(OriginalFileLength);
      }
      if (OriginalFileMd5.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(OriginalFileMd5);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PatchName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PatchName);
      }
      if (VersionTag.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(VersionTag);
      }
      if (BuildId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BuildId);
      }
      if (PatchSize != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(PatchSize);
      }
      if (PatchMd5.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(PatchMd5);
      }
      if (PatchOffset != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(PatchOffset);
      }
      if (PatchLength != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(PatchLength);
      }
      if (OriginalFileName.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(OriginalFileName);
      }
      if (OriginalFileLength != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(OriginalFileLength);
      }
      if (OriginalFileMd5.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(OriginalFileMd5);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PatchName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PatchName);
      }
      if (VersionTag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VersionTag);
      }
      if (BuildId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BuildId);
      }
      if (PatchSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PatchSize);
      }
      if (PatchMd5.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PatchMd5);
      }
      if (PatchOffset != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PatchOffset);
      }
      if (PatchLength != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PatchLength);
      }
      if (OriginalFileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginalFileName);
      }
      if (OriginalFileLength != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OriginalFileLength);
      }
      if (OriginalFileMd5.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OriginalFileMd5);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SophonPatchAssetChunk other) {
      if (other == null) {
        return;
      }
      if (other.PatchName.Length != 0) {
        PatchName = other.PatchName;
      }
      if (other.VersionTag.Length != 0) {
        VersionTag = other.VersionTag;
      }
      if (other.BuildId.Length != 0) {
        BuildId = other.BuildId;
      }
      if (other.PatchSize != 0L) {
        PatchSize = other.PatchSize;
      }
      if (other.PatchMd5.Length != 0) {
        PatchMd5 = other.PatchMd5;
      }
      if (other.PatchOffset != 0L) {
        PatchOffset = other.PatchOffset;
      }
      if (other.PatchLength != 0L) {
        PatchLength = other.PatchLength;
      }
      if (other.OriginalFileName.Length != 0) {
        OriginalFileName = other.OriginalFileName;
      }
      if (other.OriginalFileLength != 0L) {
        OriginalFileLength = other.OriginalFileLength;
      }
      if (other.OriginalFileMd5.Length != 0) {
        OriginalFileMd5 = other.OriginalFileMd5;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PatchName = input.ReadString();
            break;
          }
          case 18: {
            VersionTag = input.ReadString();
            break;
          }
          case 26: {
            BuildId = input.ReadString();
            break;
          }
          case 32: {
            PatchSize = input.ReadInt64();
            break;
          }
          case 42: {
            PatchMd5 = input.ReadString();
            break;
          }
          case 48: {
            PatchOffset = input.ReadInt64();
            break;
          }
          case 56: {
            PatchLength = input.ReadInt64();
            break;
          }
          case 66: {
            OriginalFileName = input.ReadString();
            break;
          }
          case 72: {
            OriginalFileLength = input.ReadInt64();
            break;
          }
          case 82: {
            OriginalFileMd5 = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PatchName = input.ReadString();
            break;
          }
          case 18: {
            VersionTag = input.ReadString();
            break;
          }
          case 26: {
            BuildId = input.ReadString();
            break;
          }
          case 32: {
            PatchSize = input.ReadInt64();
            break;
          }
          case 42: {
            PatchMd5 = input.ReadString();
            break;
          }
          case 48: {
            PatchOffset = input.ReadInt64();
            break;
          }
          case 56: {
            PatchLength = input.ReadInt64();
            break;
          }
          case 66: {
            OriginalFileName = input.ReadString();
            break;
          }
          case 72: {
            OriginalFileLength = input.ReadInt64();
            break;
          }
          case 82: {
            OriginalFileMd5 = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SophonUnusedAssetProperty : pb::IMessage<SophonUnusedAssetProperty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SophonUnusedAssetProperty> _parser = new pb::MessageParser<SophonUnusedAssetProperty>(() => new SophonUnusedAssetProperty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SophonUnusedAssetProperty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.Sophon.Protos.SophonPatchProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetProperty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetProperty(SophonUnusedAssetProperty other) : this() {
      versionTag_ = other.versionTag_;
      assetInfos_ = other.assetInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetProperty Clone() {
      return new SophonUnusedAssetProperty(this);
    }

    /// <summary>Field number for the "VersionTag" field.</summary>
    public const int VersionTagFieldNumber = 1;
    private string versionTag_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VersionTag {
      get { return versionTag_; }
      set {
        versionTag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "AssetInfos" field.</summary>
    public const int AssetInfosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo> _repeated_assetInfos_codec
        = pb::FieldCodec.ForMessage(18, global::Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo.Parser);
    private readonly pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo> assetInfos_ = new pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetInfo> AssetInfos {
      get { return assetInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SophonUnusedAssetProperty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SophonUnusedAssetProperty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VersionTag != other.VersionTag) return false;
      if(!assetInfos_.Equals(other.assetInfos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VersionTag.Length != 0) hash ^= VersionTag.GetHashCode();
      hash ^= assetInfos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VersionTag.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VersionTag);
      }
      assetInfos_.WriteTo(output, _repeated_assetInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VersionTag.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VersionTag);
      }
      assetInfos_.WriteTo(ref output, _repeated_assetInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VersionTag.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VersionTag);
      }
      size += assetInfos_.CalculateSize(_repeated_assetInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SophonUnusedAssetProperty other) {
      if (other == null) {
        return;
      }
      if (other.VersionTag.Length != 0) {
        VersionTag = other.VersionTag;
      }
      assetInfos_.Add(other.assetInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VersionTag = input.ReadString();
            break;
          }
          case 18: {
            assetInfos_.AddEntriesFrom(input, _repeated_assetInfos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VersionTag = input.ReadString();
            break;
          }
          case 18: {
            assetInfos_.AddEntriesFrom(ref input, _repeated_assetInfos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SophonUnusedAssetInfo : pb::IMessage<SophonUnusedAssetInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SophonUnusedAssetInfo> _parser = new pb::MessageParser<SophonUnusedAssetInfo>(() => new SophonUnusedAssetInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SophonUnusedAssetInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.Sophon.Protos.SophonPatchProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetInfo(SophonUnusedAssetInfo other) : this() {
      assets_ = other.assets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetInfo Clone() {
      return new SophonUnusedAssetInfo(this);
    }

    /// <summary>Field number for the "Assets" field.</summary>
    public const int AssetsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetFile> _repeated_assets_codec
        = pb::FieldCodec.ForMessage(10, global::Hi3Helper.Sophon.Protos.SophonUnusedAssetFile.Parser);
    private readonly pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetFile> assets_ = new pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetFile>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Hi3Helper.Sophon.Protos.SophonUnusedAssetFile> Assets {
      get { return assets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SophonUnusedAssetInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SophonUnusedAssetInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!assets_.Equals(other.assets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= assets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      assets_.WriteTo(output, _repeated_assets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      assets_.WriteTo(ref output, _repeated_assets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += assets_.CalculateSize(_repeated_assets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SophonUnusedAssetInfo other) {
      if (other == null) {
        return;
      }
      assets_.Add(other.assets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            assets_.AddEntriesFrom(input, _repeated_assets_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            assets_.AddEntriesFrom(ref input, _repeated_assets_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SophonUnusedAssetFile : pb::IMessage<SophonUnusedAssetFile>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SophonUnusedAssetFile> _parser = new pb::MessageParser<SophonUnusedAssetFile>(() => new SophonUnusedAssetFile());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SophonUnusedAssetFile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Hi3Helper.Sophon.Protos.SophonPatchProtoReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetFile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetFile(SophonUnusedAssetFile other) : this() {
      fileName_ = other.fileName_;
      fileSize_ = other.fileSize_;
      fileMd5_ = other.fileMd5_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SophonUnusedAssetFile Clone() {
      return new SophonUnusedAssetFile(this);
    }

    /// <summary>Field number for the "FileName" field.</summary>
    public const int FileNameFieldNumber = 1;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FileSize" field.</summary>
    public const int FileSizeFieldNumber = 2;
    private long fileSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long FileSize {
      get { return fileSize_; }
      set {
        fileSize_ = value;
      }
    }

    /// <summary>Field number for the "FileMd5" field.</summary>
    public const int FileMd5FieldNumber = 3;
    private string fileMd5_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FileMd5 {
      get { return fileMd5_; }
      set {
        fileMd5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SophonUnusedAssetFile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SophonUnusedAssetFile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileName != other.FileName) return false;
      if (FileSize != other.FileSize) return false;
      if (FileMd5 != other.FileMd5) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (FileSize != 0L) hash ^= FileSize.GetHashCode();
      if (FileMd5.Length != 0) hash ^= FileMd5.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (FileSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FileSize);
      }
      if (FileMd5.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FileMd5);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (FileSize != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(FileSize);
      }
      if (FileMd5.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FileMd5);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (FileSize != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(FileSize);
      }
      if (FileMd5.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileMd5);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SophonUnusedAssetFile other) {
      if (other == null) {
        return;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.FileSize != 0L) {
        FileSize = other.FileSize;
      }
      if (other.FileMd5.Length != 0) {
        FileMd5 = other.FileMd5;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 16: {
            FileSize = input.ReadInt64();
            break;
          }
          case 26: {
            FileMd5 = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 16: {
            FileSize = input.ReadInt64();
            break;
          }
          case 26: {
            FileMd5 = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
